require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BootcampsController do

  # This should return the minimal set of attributes required to create a valid
  # Bootcamp. As you add validations to Bootcamp, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BootcampsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all bootcamps as @bootcamps" do
      bootcamp = Bootcamp.create! valid_attributes
      get :index, {}, valid_session
      assigns(:bootcamps).should eq([bootcamp])
    end
  end

  describe "GET show" do
    it "assigns the requested bootcamp as @bootcamp" do
      bootcamp = Bootcamp.create! valid_attributes
      get :show, {:id => bootcamp.to_param}, valid_session
      assigns(:bootcamp).should eq(bootcamp)
    end
  end

  describe "GET new" do
    it "assigns a new bootcamp as @bootcamp" do
      get :new, {}, valid_session
      assigns(:bootcamp).should be_a_new(Bootcamp)
    end
  end

  describe "GET edit" do
    it "assigns the requested bootcamp as @bootcamp" do
      bootcamp = Bootcamp.create! valid_attributes
      get :edit, {:id => bootcamp.to_param}, valid_session
      assigns(:bootcamp).should eq(bootcamp)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Bootcamp" do
        expect {
          post :create, {:bootcamp => valid_attributes}, valid_session
        }.to change(Bootcamp, :count).by(1)
      end

      it "assigns a newly created bootcamp as @bootcamp" do
        post :create, {:bootcamp => valid_attributes}, valid_session
        assigns(:bootcamp).should be_a(Bootcamp)
        assigns(:bootcamp).should be_persisted
      end

      it "redirects to the created bootcamp" do
        post :create, {:bootcamp => valid_attributes}, valid_session
        response.should redirect_to(Bootcamp.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved bootcamp as @bootcamp" do
        # Trigger the behavior that occurs when invalid params are submitted
        Bootcamp.any_instance.stub(:save).and_return(false)
        post :create, {:bootcamp => {}}, valid_session
        assigns(:bootcamp).should be_a_new(Bootcamp)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Bootcamp.any_instance.stub(:save).and_return(false)
        post :create, {:bootcamp => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested bootcamp" do
        bootcamp = Bootcamp.create! valid_attributes
        # Assuming there are no other bootcamps in the database, this
        # specifies that the Bootcamp created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Bootcamp.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => bootcamp.to_param, :bootcamp => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested bootcamp as @bootcamp" do
        bootcamp = Bootcamp.create! valid_attributes
        put :update, {:id => bootcamp.to_param, :bootcamp => valid_attributes}, valid_session
        assigns(:bootcamp).should eq(bootcamp)
      end

      it "redirects to the bootcamp" do
        bootcamp = Bootcamp.create! valid_attributes
        put :update, {:id => bootcamp.to_param, :bootcamp => valid_attributes}, valid_session
        response.should redirect_to(bootcamp)
      end
    end

    describe "with invalid params" do
      it "assigns the bootcamp as @bootcamp" do
        bootcamp = Bootcamp.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Bootcamp.any_instance.stub(:save).and_return(false)
        put :update, {:id => bootcamp.to_param, :bootcamp => {}}, valid_session
        assigns(:bootcamp).should eq(bootcamp)
      end

      it "re-renders the 'edit' template" do
        bootcamp = Bootcamp.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Bootcamp.any_instance.stub(:save).and_return(false)
        put :update, {:id => bootcamp.to_param, :bootcamp => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested bootcamp" do
      bootcamp = Bootcamp.create! valid_attributes
      expect {
        delete :destroy, {:id => bootcamp.to_param}, valid_session
      }.to change(Bootcamp, :count).by(-1)
    end

    it "redirects to the bootcamps list" do
      bootcamp = Bootcamp.create! valid_attributes
      delete :destroy, {:id => bootcamp.to_param}, valid_session
      response.should redirect_to(bootcamps_url)
    end
  end

end
